### ISSUE TITLE
AAAA records are not resolved if the underlying connection doesn't have IPv6

### ISSUE THREAD

**Issue by jornane** [eduvpn/macos#47] opened 2018-02-24 12:31 UTC
Possibly related to #39.

When I'm on a network without native IPv6 available and I connect to a eduVPN instance with IPv6 available, the default resolver will still not try to resolve IPv6 addresses. Illustration:

	% curl v6.myip.tf
	curl: (6) Could not resolve host: v6.myip.tf

	% host v6.myip.tf
	v6.myip.tf has IPv6 address 2001:19f0:5001:229:80::1
	v6.myip.tf has IPv6 address 2001:19f0:7001:1031:80::1

	% curl 'http://[2001:19f0:5001:229:80::1]'
	2001:700:0:4108::1001

As we can see, IPv6 connectivity works fine but only if I use IPv6 addresses directly. Connections to IPv6-only hostnames will fail and connections to dualstack hostnames will go over IPv4. This applies to both Firefox and Safari. `ping6` and `traceroute6` work, also when given a hostname.

Expected behaviour:

	% curl v6.myip.tf
	2001:700:0:4108::1001

This works if the underlying connection supports IPv6.

**Comment by fkooman** [comment] 2018-02-25 08:01
If traceroute and ping6 work with a hostname it means the DNS resolving actually works?

**Comment by fkooman** [comment] 2018-02-25 08:02
Are you not running into this problem: https://en.wikipedia.org/wiki/Happy_Eyeballs ?

**Comment by jornane** [comment] 2018-02-25 16:45
@fkooman Happy Eyeballs doesn't have to do with the resolving. As you can see in the terminal output I've included, cURL returns `Could not resolve host` while host(1) can. Here's another test I came up with later.

	% curl -v6 myip.tf
	* Rebuilt URL to: myip.tf/
	*   Trying ::ffff:45.76.33.74...
	* TCP_NODELAY set
	* Connected to myip.tf (::ffff:45.76.33.74) port 80 (#0)
	> GET / HTTP/1.1
	> Host: myip.tf
	> User-Agent: curl/7.54.0
	> Accept: */*
	>
	< HTTP/1.1 200 OK
	< X-Powered-By: PHP/7.0.14
	< Content-Length: 14
	< Vary: Accept, Accept-Encoding
	< Access-Control-Allow-Headers: Accept
	< Access-Control-Allow-Methods: GET
	< Access-Control-Allow-Origin: *
	< Content-Type: text/plain;charset=ASCII
	< Date: Sun, 25 Feb 2018 16:44:49 GMT
	< Server: lighttpd/1 (FreeBSD)
	<
	158.36.18.99
	* Connection #0 to host myip.tf left intact

**Comment by jornane** [comment] 2018-02-26 14:26
More digging:

On a machine with IPv6 (and no eduVPN connected)

	$ scutil --dns
	[…]
	DNS configuration (for scoped queries)

	resolver #1
	  search domain[0] : uninett.no
	  nameserver[0] : 2001:700:0:ff00::1
	  nameserver[1] : 2001:700:0:ff00::2
	  if_index : 6 (en4)
	  flags    : Scoped, Request A records, Request AAAA records
	  reach    : 0x00000002 (Reachable)

On a machine with eduVPN connected to an IPv4-only network:

	$ scutil --dns
	[…]
	DNS configuration (for scoped queries)

	resolver #1
	  search domain[0] : openvpn
	  nameserver[0] : 158.38.0.1
	  nameserver[1] : 158.38.0.2
	  if_index : 5 (en0)
	  flags    : Scoped, Request A records
	  reach    : 0x00000002 (Reachable)

(All mentioned IPs are DNS resolvers that can be used within the Norwegian research network)

Right now I don't have the possibility to connect eduVPN to a network with IPv6, but I hope I will be able soon.

**Comment by jornane** [comment] 2018-02-28 09:36
On a connection with native IPv6 and a connection to eduVPN:

	% scutil --dns
	[…]
	DNS configuration (for scoped queries)

	resolver #1
	  search domain[0] : openvpn
	  nameserver[0] : 158.38.0.1
	  nameserver[1] : 158.38.0.2
	  if_index : 16 (en5)
	  flags    : Scoped, Request A records, Request AAAA records
	  reach    : 0x00000000 (Not Reachable)

**Comment by jornane** [comment] 2018-06-15 14:05
Not fixed in Version 0.1.3 (0.1.3)

**Comment by johankool** [comment] 2018-08-29 11:09
```Wed Aug 29 12:32:23 2018 /sbin/ifconfig utun4 145.101.113.68 145.101.113.68 netmask 255.255.255.192 mtu 1500 up
Wed Aug 29 12:32:23 2018 /sbin/route add -net 145.101.113.64 145.101.113.68 255.255.255.192
add net 145.101.113.64: gateway 145.101.113.68
Wed Aug 29 12:32:23 2018 /sbin/ifconfig utun4 inet6 2001:610:188:70::1:1002/112
Wed Aug 29 12:32:23 2018 add_route_ipv6(2001:610:188:70::1:0/112 -> 2001:610:188:70::1:1002 metric 0) dev utun4
Wed Aug 29 12:32:23 2018 /sbin/route add -inet6 2001:610:188:70::1:0 -prefixlen 112 -iface utun4
route: writing to routing socket: File exists
add net 2001:610:188:70::1:0: gateway utun4: File exists
```

I suspect that file exists error is the cause.

**Comment by jornane** [comment] 2018-08-29 16:13
> Hm, weird. I do indeed still see the issue. However, if you go to the Network prefpane and look under DNS the expected IPv6 DNS servers are listed. Also here they seem to appear correctly:

IPv6 resolvers are missing, even when using eduVPN on a connection that already has IPv6 available. However, I think that is a separate problem. The problem here is that the available resolver, be it IPv4 or IPv6, is not used for AAAA lookups.

On an eduVPN connection with IPv6 connectivity, `scutil --dns` should show

	Scoped, Request A records, Request AAAA records

But instead it shows

	Scoped, Request A records

**Comment by fkooman** [comment] 2018-08-29 18:15
Wow, that is crazy! I had no idea the DNS resolver on macOS could be configured this way. What could have possibly been the reason they designed it like this?

@jornane do you know why `curl` doesn't work but `host` does?

**Comment by fkooman** [comment] 2018-08-29 18:16
https://github.com/Tunnelblick/Tunnelblick/issues/440

**Comment by fkooman** [comment] 2018-08-29 18:17
https://github.com/Tunnelblick/Tunnelblick/issues/379

**Comment by fkooman** [comment] 2018-08-29 18:17
So I think it may be solved in Tunnelblick already, now we have to find out what they did to fix it :)

**Comment by fkooman** [comment] 2018-08-29 19:14
What a "curious" way to implement things...

**Comment by fkooman** [comment] 2018-08-29 19:18
> I suspect that file exists error is the cause.

What makes you suspect this?

**Comment by johankool** [comment] 2018-08-29 19:57
If I turn IPv6 on in my local router, the network prefpane shows an IPv6 address and router. Also, everything works as expected and the AAAA flag is present. 

When the issue occurs the IPv6 address and router don’t show up in the network prefpane. The add_ route_ipv6 seems to be what sets that. Seemed reasonable to me that there is a connection between these things.

**Comment by johankool** [comment] 2018-08-29 19:59
Issue 379 of Tunnelblick: I had added support for that (DNS6) to our copy of the script. I’ll compare that with theirs tomorrow.

**Comment by fkooman** [comment] 2018-08-29 20:00
But as shown by @jornane  IPv6 traffic *does* work. So that can't be it, right?

**Comment by fkooman** [comment] 2018-08-29 20:01
> Issue 379 of Tunnelblick: I had added support for that (DNS6) to our copy of the script. I’ll compare that with theirs tomorrow.

Make sure you also accept IPv6 addresses in "DNS" push replies, not only DNS6.

**Comment by johankool** [comment] 2018-08-29 20:14
IPv6 is disabled on my local router. No ideas how that could work outside the VPN tunnel. So, not sure what happens there. 

I do think I do indeed accept IPv6 addresses in DNS too. Will double check tomorrow. That 440 issue does seem to have some good things to try. 👍

**Comment by johankool** [comment] 2018-08-30 07:55
The IPv6 issue is resolved with the script from https://github.com/Tunnelblick/Tunnelblick/pull/452. The  add_route_ipv6/File exits error remains. Not sure if that's something to worry about or not. If so, I think it's better to create a new issue for that.

**Comment by jornane** [comment] 2019-03-06 22:03
Regression: This problem is back in version 1.2.

**Comment by nshtg** [comment] 2019-03-17 00:33
@johankool I can confirm this issue is back with the most recent versions of tunnelblick, including beta versions!

**Comment by efef** [comment] 2019-03-18 10:48
This issue was initially 'solved' by using tunnelblick beta-scripts (https://github.com/Tunnelblick/Tunnelblick/pull/452) Unfortunately these scripts introduced other issues, so we reverted back. Somebody better try to 'fix' it in the current start/stop scripts.

**Comment by efef** [comment] 2019-04-02 10:36
It seems MacOS only allows IPv6 lookups through the tunnel when the local NIC has IPv6. I read here on this page: https://www.sixxs.net/forum/?msg=setup-10869082
"The moment this changes is the moment you have an IPv6 address on an officially managed interface.  So despite having a tun0 with an IPv6 address and an inet6 default route it will not do AAAA lookups.   Workaround:  set the IPv6 configuration to Manual and just put a 2001:db8::1 in the address field of your wifi or ethernet."

So we need to find out how we can 'force' IPv6 lookups through VPN-connection.

**Comment by efef** [comment] 2019-04-02 10:51
here somebody posts a solution to 'fix' it, based on how viscosity manages it:
https://apple.stackexchange.com/questions/309430/ipv6-dns-resolution-on-macos-high-sierra

**Comment by johankool** [comment] 2019-10-31 14:16
Fixed in https://github.com/eduvpn/ios/pull/114 which uses entirely new mechanism to setup VPN connection using Network Extensions. That should also resolve this problem.

**Closed by johankool** 2019-10-31 14:16 UTC
