### ISSUE TITLE
back button not working

### ISSUE THREAD

**Issue by efef** [eduvpn/macos#133] opened 2018-09-28 09:02 UTC
After a few connects/disconnect to the frkovpn VPN the back button (top left) isn't working. I can still "connect", but can't go back.

<img width="435" alt="screen shot 2018-09-28 at 10 57 21" src="https://user-images.githubusercontent.com/3393474/46198925-e3e18900-c30d-11e8-84fb-4a2f2fd93227.png">

**Comment by efef** [comment] 2018-09-28 09:52
when trying to connect a few times to frkovpn it is quite trivial to get the GUI in an unresponsive state. Sometimes I even get this screen:
<img width="441" alt="screen shot 2018-09-28 at 11 51 04" src="https://user-images.githubusercontent.com/3393474/46201659-f9a67c80-c314-11e8-8bb8-d856842e2e59.png">

**Comment by johankool** [comment] 2018-10-01 15:03
Reproduced: happens when authenticating with provider is triggered due to revoking.

**Comment by johankool** [comment] 2019-01-16 13:46
Fixed in #178

**Closed by johankool** 2019-01-16 13:46 UTC
